###############################################################################
# Created by write_sdc
# Mon Aug 22 02:31:30 2022
###############################################################################
current_design controller_unit
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clock -period 17.0000 
set_clock_uncertainty 0.2500 clock
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {io_control_trigger_in}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {io_latch_data_in}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {io_mosi_in}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {io_reset_n_in}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {io_sclk_in}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ss_n_in}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[0]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[100]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[101]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[102]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[103]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[104]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[105]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[106]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[107]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[108]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[109]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[10]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[110]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[111]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[112]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[113]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[114]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[115]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[116]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[117]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[118]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[119]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[11]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[120]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[121]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[122]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[123]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[124]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[125]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[126]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[127]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[12]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[13]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[14]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[15]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[16]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[17]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[18]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[19]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[1]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[20]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[21]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[22]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[23]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[24]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[25]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[26]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[27]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[28]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[29]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[2]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[30]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[31]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[32]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[33]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[34]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[35]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[36]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[37]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[38]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[39]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[3]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[40]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[41]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[42]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[43]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[44]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[45]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[46]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[47]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[48]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[49]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[4]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[50]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[51]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[52]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[53]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[54]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[55]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[56]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[57]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[58]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[59]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[5]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[60]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[61]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[62]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[63]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[64]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[65]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[66]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[67]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[68]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[69]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[6]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[70]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[71]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[72]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[73]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[74]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[75]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[76]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[77]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[78]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[79]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[7]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[80]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[81]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[82]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[83]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[84]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[85]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[86]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[87]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[88]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[89]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[8]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[90]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[91]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[92]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[93]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[94]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[95]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[96]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[97]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[98]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[99]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_data_in[9]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[0]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[100]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[101]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[102]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[103]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[104]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[105]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[106]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[107]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[108]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[109]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[10]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[110]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[111]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[112]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[113]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[114]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[115]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[116]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[117]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[118]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[119]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[11]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[120]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[121]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[122]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[123]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[124]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[125]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[126]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[127]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[12]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[13]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[14]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[15]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[16]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[17]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[18]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[19]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[1]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[20]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[21]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[22]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[23]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[24]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[25]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[26]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[27]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[28]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[29]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[2]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[30]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[31]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[32]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[33]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[34]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[35]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[36]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[37]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[38]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[39]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[3]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[40]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[41]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[42]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[43]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[44]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[45]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[46]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[47]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[48]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[49]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[4]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[50]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[51]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[52]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[53]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[54]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[55]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[56]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[57]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[58]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[59]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[5]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[60]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[61]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[62]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[63]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[64]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[65]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[66]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[67]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[68]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[69]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[6]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[70]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[71]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[72]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[73]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[74]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[75]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[76]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[77]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[78]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[79]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[7]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[80]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[81]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[82]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[83]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[84]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[85]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[86]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[87]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[88]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[89]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[8]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[90]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[91]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[92]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[93]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[94]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[95]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[96]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[97]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[98]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[99]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {la_oenb[9]}]
set_input_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {user_clock2}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {clock_out[0]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {clock_out[1]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {clock_out[2]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {clock_out[3]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {clock_out[4]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {clock_out[5]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {clock_out[6]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {clock_out[7]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {clock_out[8]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {clock_out[9]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {col_select_left[0]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {col_select_left[1]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {col_select_left[2]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {col_select_left[3]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {col_select_left[4]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {col_select_left[5]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {col_select_right[0]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {col_select_right[1]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {col_select_right[2]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {col_select_right[3]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {col_select_right[4]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {col_select_right[5]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_left[0]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_left[10]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_left[11]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_left[12]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_left[13]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_left[14]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_left[15]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_left[1]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_left[2]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_left[3]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_left[4]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_left[5]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_left[6]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_left[7]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_left[8]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_left[9]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_right[0]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_right[10]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_right[11]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_right[12]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_right[13]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_right[14]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_right[15]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_right[1]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_right[2]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_right[3]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_right[4]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_right[5]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_right[6]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_right[7]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_right[8]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {data_out_right[9]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {inverter_select[0]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {inverter_select[1]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {inverter_select[2]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {inverter_select[3]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {inverter_select[4]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {inverter_select[5]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {inverter_select[6]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {inverter_select[7]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {inverter_select[8]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {inverter_select[9]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {io_control_trigger_oeb}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {io_driver_io_oeb[0]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {io_driver_io_oeb[1]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {io_driver_io_oeb[2]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {io_driver_io_oeb[3]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {io_driver_io_oeb[4]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {io_driver_io_oeb[5]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {io_driver_io_oeb[6]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {io_driver_io_oeb[7]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {io_driver_io_oeb[8]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {io_driver_io_oeb[9]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {io_latch_data_oeb}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {io_miso_oeb}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {io_miso_out}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {io_mosi_oeb}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {io_reset_n_oeb}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {io_sclk_oeb}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ss_n_oeb}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {io_update_cycle_complete_oeb}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {io_update_cycle_complete_out}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mask_select_left[0]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mask_select_left[1]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mask_select_left[2]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mask_select_right[0]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mask_select_right[1]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mask_select_right[2]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_address_left[0]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_address_left[1]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_address_left[2]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_address_left[3]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_address_left[4]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_address_left[5]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_address_left[6]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_address_right[0]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_address_right[1]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_address_right[2]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_address_right[3]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_address_right[4]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_address_right[5]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_address_right[6]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_dot_write_n[0]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_dot_write_n[1]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_dot_write_n[2]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_dot_write_n[3]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_dot_write_n[4]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_dot_write_n[5]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_dot_write_n[6]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_dot_write_n[7]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_dot_write_n[8]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_dot_write_n[9]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_sel_col_address_left[0]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_sel_col_address_left[1]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_sel_col_address_left[2]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_sel_col_address_left[3]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_sel_col_address_left[4]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_sel_col_address_left[5]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_sel_col_address_left[6]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_sel_col_address_right[0]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_sel_col_address_right[1]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_sel_col_address_right[2]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_sel_col_address_right[3]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_sel_col_address_right[4]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_sel_col_address_right[5]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_sel_col_address_right[6]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_sel_write_n[0]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_sel_write_n[1]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_sel_write_n[2]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_sel_write_n[3]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_sel_write_n[4]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_sel_write_n[5]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_sel_write_n[6]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_sel_write_n[7]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_sel_write_n[8]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_sel_write_n[9]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_write_n[0]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_write_n[1]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_write_n[2]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_write_n[3]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_write_n[4]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_write_n[5]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_write_n[6]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_write_n[7]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_write_n[8]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {mem_write_n[9]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {output_active_left}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {output_active_right}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {row_col_select[0]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {row_col_select[1]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {row_col_select[2]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {row_col_select[3]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {row_col_select[4]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {row_col_select[5]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {row_col_select[6]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {row_col_select[7]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {row_col_select[8]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {row_col_select[9]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {row_select_left[0]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {row_select_left[1]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {row_select_left[2]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {row_select_left[3]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {row_select_left[4]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {row_select_left[5]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {row_select_right[0]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {row_select_right[1]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {row_select_right[2]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {row_select_right[3]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {row_select_right[4]}]
set_output_delay 3.4000 -clock [get_clocks {clock}] -add_delay [get_ports {row_select_right[5]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {io_control_trigger_oeb}]
set_load -pin_load 0.0334 [get_ports {io_latch_data_oeb}]
set_load -pin_load 0.0334 [get_ports {io_miso_oeb}]
set_load -pin_load 0.0334 [get_ports {io_miso_out}]
set_load -pin_load 0.0334 [get_ports {io_mosi_oeb}]
set_load -pin_load 0.0334 [get_ports {io_reset_n_oeb}]
set_load -pin_load 0.0334 [get_ports {io_sclk_oeb}]
set_load -pin_load 0.0334 [get_ports {io_ss_n_oeb}]
set_load -pin_load 0.0334 [get_ports {io_update_cycle_complete_oeb}]
set_load -pin_load 0.0334 [get_ports {io_update_cycle_complete_out}]
set_load -pin_load 0.0334 [get_ports {output_active_left}]
set_load -pin_load 0.0334 [get_ports {output_active_right}]
set_load -pin_load 0.0334 [get_ports {clock_out[9]}]
set_load -pin_load 0.0334 [get_ports {clock_out[8]}]
set_load -pin_load 0.0334 [get_ports {clock_out[7]}]
set_load -pin_load 0.0334 [get_ports {clock_out[6]}]
set_load -pin_load 0.0334 [get_ports {clock_out[5]}]
set_load -pin_load 0.0334 [get_ports {clock_out[4]}]
set_load -pin_load 0.0334 [get_ports {clock_out[3]}]
set_load -pin_load 0.0334 [get_ports {clock_out[2]}]
set_load -pin_load 0.0334 [get_ports {clock_out[1]}]
set_load -pin_load 0.0334 [get_ports {clock_out[0]}]
set_load -pin_load 0.0334 [get_ports {col_select_left[5]}]
set_load -pin_load 0.0334 [get_ports {col_select_left[4]}]
set_load -pin_load 0.0334 [get_ports {col_select_left[3]}]
set_load -pin_load 0.0334 [get_ports {col_select_left[2]}]
set_load -pin_load 0.0334 [get_ports {col_select_left[1]}]
set_load -pin_load 0.0334 [get_ports {col_select_left[0]}]
set_load -pin_load 0.0334 [get_ports {col_select_right[5]}]
set_load -pin_load 0.0334 [get_ports {col_select_right[4]}]
set_load -pin_load 0.0334 [get_ports {col_select_right[3]}]
set_load -pin_load 0.0334 [get_ports {col_select_right[2]}]
set_load -pin_load 0.0334 [get_ports {col_select_right[1]}]
set_load -pin_load 0.0334 [get_ports {col_select_right[0]}]
set_load -pin_load 0.0334 [get_ports {data_out_left[15]}]
set_load -pin_load 0.0334 [get_ports {data_out_left[14]}]
set_load -pin_load 0.0334 [get_ports {data_out_left[13]}]
set_load -pin_load 0.0334 [get_ports {data_out_left[12]}]
set_load -pin_load 0.0334 [get_ports {data_out_left[11]}]
set_load -pin_load 0.0334 [get_ports {data_out_left[10]}]
set_load -pin_load 0.0334 [get_ports {data_out_left[9]}]
set_load -pin_load 0.0334 [get_ports {data_out_left[8]}]
set_load -pin_load 0.0334 [get_ports {data_out_left[7]}]
set_load -pin_load 0.0334 [get_ports {data_out_left[6]}]
set_load -pin_load 0.0334 [get_ports {data_out_left[5]}]
set_load -pin_load 0.0334 [get_ports {data_out_left[4]}]
set_load -pin_load 0.0334 [get_ports {data_out_left[3]}]
set_load -pin_load 0.0334 [get_ports {data_out_left[2]}]
set_load -pin_load 0.0334 [get_ports {data_out_left[1]}]
set_load -pin_load 0.0334 [get_ports {data_out_left[0]}]
set_load -pin_load 0.0334 [get_ports {data_out_right[15]}]
set_load -pin_load 0.0334 [get_ports {data_out_right[14]}]
set_load -pin_load 0.0334 [get_ports {data_out_right[13]}]
set_load -pin_load 0.0334 [get_ports {data_out_right[12]}]
set_load -pin_load 0.0334 [get_ports {data_out_right[11]}]
set_load -pin_load 0.0334 [get_ports {data_out_right[10]}]
set_load -pin_load 0.0334 [get_ports {data_out_right[9]}]
set_load -pin_load 0.0334 [get_ports {data_out_right[8]}]
set_load -pin_load 0.0334 [get_ports {data_out_right[7]}]
set_load -pin_load 0.0334 [get_ports {data_out_right[6]}]
set_load -pin_load 0.0334 [get_ports {data_out_right[5]}]
set_load -pin_load 0.0334 [get_ports {data_out_right[4]}]
set_load -pin_load 0.0334 [get_ports {data_out_right[3]}]
set_load -pin_load 0.0334 [get_ports {data_out_right[2]}]
set_load -pin_load 0.0334 [get_ports {data_out_right[1]}]
set_load -pin_load 0.0334 [get_ports {data_out_right[0]}]
set_load -pin_load 0.0334 [get_ports {inverter_select[9]}]
set_load -pin_load 0.0334 [get_ports {inverter_select[8]}]
set_load -pin_load 0.0334 [get_ports {inverter_select[7]}]
set_load -pin_load 0.0334 [get_ports {inverter_select[6]}]
set_load -pin_load 0.0334 [get_ports {inverter_select[5]}]
set_load -pin_load 0.0334 [get_ports {inverter_select[4]}]
set_load -pin_load 0.0334 [get_ports {inverter_select[3]}]
set_load -pin_load 0.0334 [get_ports {inverter_select[2]}]
set_load -pin_load 0.0334 [get_ports {inverter_select[1]}]
set_load -pin_load 0.0334 [get_ports {inverter_select[0]}]
set_load -pin_load 0.0334 [get_ports {io_driver_io_oeb[9]}]
set_load -pin_load 0.0334 [get_ports {io_driver_io_oeb[8]}]
set_load -pin_load 0.0334 [get_ports {io_driver_io_oeb[7]}]
set_load -pin_load 0.0334 [get_ports {io_driver_io_oeb[6]}]
set_load -pin_load 0.0334 [get_ports {io_driver_io_oeb[5]}]
set_load -pin_load 0.0334 [get_ports {io_driver_io_oeb[4]}]
set_load -pin_load 0.0334 [get_ports {io_driver_io_oeb[3]}]
set_load -pin_load 0.0334 [get_ports {io_driver_io_oeb[2]}]
set_load -pin_load 0.0334 [get_ports {io_driver_io_oeb[1]}]
set_load -pin_load 0.0334 [get_ports {io_driver_io_oeb[0]}]
set_load -pin_load 0.0334 [get_ports {mask_select_left[2]}]
set_load -pin_load 0.0334 [get_ports {mask_select_left[1]}]
set_load -pin_load 0.0334 [get_ports {mask_select_left[0]}]
set_load -pin_load 0.0334 [get_ports {mask_select_right[2]}]
set_load -pin_load 0.0334 [get_ports {mask_select_right[1]}]
set_load -pin_load 0.0334 [get_ports {mask_select_right[0]}]
set_load -pin_load 0.0334 [get_ports {mem_address_left[6]}]
set_load -pin_load 0.0334 [get_ports {mem_address_left[5]}]
set_load -pin_load 0.0334 [get_ports {mem_address_left[4]}]
set_load -pin_load 0.0334 [get_ports {mem_address_left[3]}]
set_load -pin_load 0.0334 [get_ports {mem_address_left[2]}]
set_load -pin_load 0.0334 [get_ports {mem_address_left[1]}]
set_load -pin_load 0.0334 [get_ports {mem_address_left[0]}]
set_load -pin_load 0.0334 [get_ports {mem_address_right[6]}]
set_load -pin_load 0.0334 [get_ports {mem_address_right[5]}]
set_load -pin_load 0.0334 [get_ports {mem_address_right[4]}]
set_load -pin_load 0.0334 [get_ports {mem_address_right[3]}]
set_load -pin_load 0.0334 [get_ports {mem_address_right[2]}]
set_load -pin_load 0.0334 [get_ports {mem_address_right[1]}]
set_load -pin_load 0.0334 [get_ports {mem_address_right[0]}]
set_load -pin_load 0.0334 [get_ports {mem_dot_write_n[9]}]
set_load -pin_load 0.0334 [get_ports {mem_dot_write_n[8]}]
set_load -pin_load 0.0334 [get_ports {mem_dot_write_n[7]}]
set_load -pin_load 0.0334 [get_ports {mem_dot_write_n[6]}]
set_load -pin_load 0.0334 [get_ports {mem_dot_write_n[5]}]
set_load -pin_load 0.0334 [get_ports {mem_dot_write_n[4]}]
set_load -pin_load 0.0334 [get_ports {mem_dot_write_n[3]}]
set_load -pin_load 0.0334 [get_ports {mem_dot_write_n[2]}]
set_load -pin_load 0.0334 [get_ports {mem_dot_write_n[1]}]
set_load -pin_load 0.0334 [get_ports {mem_dot_write_n[0]}]
set_load -pin_load 0.0334 [get_ports {mem_sel_col_address_left[6]}]
set_load -pin_load 0.0334 [get_ports {mem_sel_col_address_left[5]}]
set_load -pin_load 0.0334 [get_ports {mem_sel_col_address_left[4]}]
set_load -pin_load 0.0334 [get_ports {mem_sel_col_address_left[3]}]
set_load -pin_load 0.0334 [get_ports {mem_sel_col_address_left[2]}]
set_load -pin_load 0.0334 [get_ports {mem_sel_col_address_left[1]}]
set_load -pin_load 0.0334 [get_ports {mem_sel_col_address_left[0]}]
set_load -pin_load 0.0334 [get_ports {mem_sel_col_address_right[6]}]
set_load -pin_load 0.0334 [get_ports {mem_sel_col_address_right[5]}]
set_load -pin_load 0.0334 [get_ports {mem_sel_col_address_right[4]}]
set_load -pin_load 0.0334 [get_ports {mem_sel_col_address_right[3]}]
set_load -pin_load 0.0334 [get_ports {mem_sel_col_address_right[2]}]
set_load -pin_load 0.0334 [get_ports {mem_sel_col_address_right[1]}]
set_load -pin_load 0.0334 [get_ports {mem_sel_col_address_right[0]}]
set_load -pin_load 0.0334 [get_ports {mem_sel_write_n[9]}]
set_load -pin_load 0.0334 [get_ports {mem_sel_write_n[8]}]
set_load -pin_load 0.0334 [get_ports {mem_sel_write_n[7]}]
set_load -pin_load 0.0334 [get_ports {mem_sel_write_n[6]}]
set_load -pin_load 0.0334 [get_ports {mem_sel_write_n[5]}]
set_load -pin_load 0.0334 [get_ports {mem_sel_write_n[4]}]
set_load -pin_load 0.0334 [get_ports {mem_sel_write_n[3]}]
set_load -pin_load 0.0334 [get_ports {mem_sel_write_n[2]}]
set_load -pin_load 0.0334 [get_ports {mem_sel_write_n[1]}]
set_load -pin_load 0.0334 [get_ports {mem_sel_write_n[0]}]
set_load -pin_load 0.0334 [get_ports {mem_write_n[9]}]
set_load -pin_load 0.0334 [get_ports {mem_write_n[8]}]
set_load -pin_load 0.0334 [get_ports {mem_write_n[7]}]
set_load -pin_load 0.0334 [get_ports {mem_write_n[6]}]
set_load -pin_load 0.0334 [get_ports {mem_write_n[5]}]
set_load -pin_load 0.0334 [get_ports {mem_write_n[4]}]
set_load -pin_load 0.0334 [get_ports {mem_write_n[3]}]
set_load -pin_load 0.0334 [get_ports {mem_write_n[2]}]
set_load -pin_load 0.0334 [get_ports {mem_write_n[1]}]
set_load -pin_load 0.0334 [get_ports {mem_write_n[0]}]
set_load -pin_load 0.0334 [get_ports {row_col_select[9]}]
set_load -pin_load 0.0334 [get_ports {row_col_select[8]}]
set_load -pin_load 0.0334 [get_ports {row_col_select[7]}]
set_load -pin_load 0.0334 [get_ports {row_col_select[6]}]
set_load -pin_load 0.0334 [get_ports {row_col_select[5]}]
set_load -pin_load 0.0334 [get_ports {row_col_select[4]}]
set_load -pin_load 0.0334 [get_ports {row_col_select[3]}]
set_load -pin_load 0.0334 [get_ports {row_col_select[2]}]
set_load -pin_load 0.0334 [get_ports {row_col_select[1]}]
set_load -pin_load 0.0334 [get_ports {row_col_select[0]}]
set_load -pin_load 0.0334 [get_ports {row_select_left[5]}]
set_load -pin_load 0.0334 [get_ports {row_select_left[4]}]
set_load -pin_load 0.0334 [get_ports {row_select_left[3]}]
set_load -pin_load 0.0334 [get_ports {row_select_left[2]}]
set_load -pin_load 0.0334 [get_ports {row_select_left[1]}]
set_load -pin_load 0.0334 [get_ports {row_select_left[0]}]
set_load -pin_load 0.0334 [get_ports {row_select_right[5]}]
set_load -pin_load 0.0334 [get_ports {row_select_right[4]}]
set_load -pin_load 0.0334 [get_ports {row_select_right[3]}]
set_load -pin_load 0.0334 [get_ports {row_select_right[2]}]
set_load -pin_load 0.0334 [get_ports {row_select_right[1]}]
set_load -pin_load 0.0334 [get_ports {row_select_right[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {io_control_trigger_in}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {io_latch_data_in}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {io_mosi_in}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {io_reset_n_in}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {io_sclk_in}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {io_ss_n_in}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {user_clock2}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[127]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[126]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[125]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[124]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[123]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[122]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[121]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[120]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[119]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[118]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[117]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[116]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[115]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[114]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[113]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[112]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[111]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[110]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[109]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[108]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[107]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[106]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[105]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[104]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[103]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[102]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[101]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[100]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[99]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[98]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[97]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[96]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[95]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[94]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[93]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[92]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[91]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[90]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[89]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[88]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[87]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[86]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[85]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[84]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[83]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[82]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[81]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[80]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[79]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[78]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[77]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[76]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[75]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[74]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[73]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[72]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[71]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[70]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[69]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[68]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[67]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[66]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[65]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[64]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[63]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[62]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[61]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[60]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[59]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[58]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[57]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[56]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[55]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[54]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[53]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[52]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[51]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[50]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[49]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[48]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[47]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[46]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[45]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[44]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[43]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[42]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[41]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[40]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[39]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[38]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[37]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[36]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[35]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[34]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[33]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[32]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_data_in[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[127]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[126]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[125]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[124]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[123]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[122]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[121]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[120]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[119]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[118]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[117]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[116]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[115]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[114]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[113]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[112]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[111]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[110]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[109]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[108]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[107]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[106]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[105]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[104]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[103]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[102]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[101]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[100]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[99]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[98]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[97]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[96]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[95]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[94]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[93]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[92]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[91]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[90]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[89]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[88]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[87]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[86]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[85]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[84]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[83]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[82]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[81]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[80]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[79]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[78]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[77]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[76]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[75]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[74]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[73]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[72]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[71]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[70]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[69]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[68]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[67]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[66]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[65]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[64]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[63]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[62]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[61]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[60]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[59]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[58]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[57]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[56]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[55]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[54]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[53]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[52]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[51]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[50]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[49]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[48]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[47]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[46]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[45]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[44]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[43]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[42]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[41]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[40]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[39]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[38]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[37]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[36]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[35]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[34]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[33]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[32]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {la_oenb[0]}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_fanout 10.0000 [current_design]
